apiVersion: apidiscovery.k8s.io/v2
kind: APIGroupDiscoveryList
Items:
  - Versions:
      - Version: v1
        Resources:
          - Resource: pods
            ResponseKind:
              group: ""
              version: v1
              kind: Pod
            Scope: Namespaced
            SingularResource: pod
            Verbs:
              - get
              - list
              - create
              - update
              - delete
            ShortNames:
              - po
            Categories:
              - all
          - Resource: replicasets
            ResponseKind:
              version: v1
              kind: ReplicaSet
            Scope: Namespaced
            SingularResource: replicaset
            Verbs:
              - get
              - list
              - create
              - update
              - delete
            ShortNames:
              - rs
            Categories:
              - all
          - Resource: ingresses
            ResponseKind:
              version: v1
              kind: Ingress
            Scope: Namespaced
            SingularResource: ingress
            Verbs:
              - get
              - list
              - create
              - update
              - delete
            ShortNames:
              - ing
            Categories:
              - all
          - Resource: configmaps
            ResponseKind:
              version: v1
              kind: ConfigMap
            Scope: Namespaced
            SingularResource: configmap
            Verbs:
              - get
              - list
              - create
              - update
              - delete
            ShortNames:
              - cm
            Categories:
              - all
