apiVersion: apidiscovery.k8s.io/v2
kind: APIGroupDiscoveryList
Items:
  - creationTimestamp:
    Versions:
      - Version: v1
        Resources:
          - Resource: pods
            ResponseKind:
              group: ""
              version: v1
              kind: Pod
            Scope: Namespaced
            SingularResource: pod
            Verbs:
              - get
              - list
              - create
              - update
              - delete
            ShortNames:
              - po
            Categories:
              - all
            Subresources:
        Freshness: ""
